import Map from 'components/KakaoMap';
import { toJS } from 'mobx';
import { inject } from 'mobx-react';
import { observer } from 'mobx-react-lite';
import type { NextPage } from 'next';
import Head from 'next/head';
import { UserStore } from 'store';

import styled from 'styled-components';

const StyledDiv = styled.div`
  color: red;
`;

interface HomeProps {
  user: UserStore;
}

const Home: NextPage = (props: HomeProps) => {
  const { user } = props;

  const { userData } = user;
  console.log(toJS(userData));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <StyledDiv>ㅎ이</StyledDiv>
        <Map />
      </main>
    </div>
  );
};

export default inject('user')(observer(Home));
